export enum ActionTypeSelectedAudios {
  PLAY_BACK_OBJ = "PLAY_BACK_OBJ",
  SOUND_OBJ = "SOUND_OBJ",
  CURRENT_AUDIO = "CURRENT_AUDIO",
  IS_PLAYING = "IS_PLAYING",
  CURRENT_INDEX = "CURRENT_INDEX",
  PLAY_BACK_POSITION = "PLAY_BACK_POSITION",
  PLAY_BACK_DURATION = "PLAY_BACK_DURATION",
  ONPLAY_BACK_STATUS_UPDATE = "ONPLAY_BACK_STATUS_UPDATE",
}
